In [1]:
import numpy as np
import torch

In [3]:
list=[3,7,8,9]
ary=np.array(list)


In [4]:
ary

array([3, 7, 8, 9])

In [17]:
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [6]:
tensors=torch.from_numpy(ary)
tensors

tensor([3, 7, 8, 9], dtype=torch.int32)

In [7]:
tensors[2]

tensor(8, dtype=torch.int32)

In [9]:
tensors[1:2]

tensor([7], dtype=torch.int32)

In [13]:
tensors[3]=100

In [14]:
tensors

tensor([  3,   7,   8, 100], dtype=torch.int32)

In [15]:
tensor_ary=torch.tensor(ary)
tensor_ary

tensor([  3,   7,   8, 100], dtype=torch.int32)

In [18]:
a=torch.tensor([6,5,7], dtype=torch.int )
b=torch.tensor([3,10,7], dtype=torch.int )
print(a+b)

tensor([ 9, 15, 14], dtype=torch.int32)


In [19]:
addition=torch.add(a,b)
addition


tensor([ 9, 15, 14], dtype=torch.int32)

In [ ]:
s= torch.add(a,b).