# tensor is a function in the PyTorch library that creates a new tensor object from the input data.


##            torch.tensor(data, dtype=None, device=None, requires_grad=False)

Parameters:

data: Input data for the tensor, which can be a Python list, NumPy ndarray, scalar value, or another tensor.

dtype: Data type of the tensor elements (default: None, which infers the data type from the input data).

device: Device (CPU or GPU) on which the tensor will be created (default: None, which creates the tensor on the CPU).

requires_grad: Boolean flag indicating whether the tensor will require gradient computation for automatic differentiation (default: False).

pin_memory: Boolean flag indicating whether to allocate the tensor in pinned memory (default: False).

In [38]:
import numpy as np
import torch

In [39]:
list=[3,7,8,9]
ary=np.array(list)


In [43]:
ary

array([3, 7, 8, 9])

In [4]:
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [44]:
tensors=torch.from_numpy(ary)
tensors

tensor([3, 7, 8, 9], dtype=torch.int32)

In [6]:
tensors[2]

tensor(8, dtype=torch.int32)

In [7]:
tensors[1:2]

tensor([7], dtype=torch.int32)

In [8]:
tensors[3]=100

In [9]:
tensors

tensor([  3,   7,   8, 100], dtype=torch.int32)

In [10]:
tensor_ary=torch.tensor(ary)
tensor_ary

tensor([  3,   7,   8, 100], dtype=torch.int32)

# Addition

In [37]:
a=torch.tensor([6,5,7], dtype=torch.int )
b=torch.tensor([3,10,7], dtype=torch.int )
print(a+b)

tensor([ 9, 15, 14])


In [12]:
addition=torch.add(a,b)
addition


tensor([ 9, 15, 14], dtype=torch.int32)

In [31]:
s=torch.add(a,b).sum()
s

tensor(38)

# Multiplication

In [ ]:

y= torch.tensor([5,5,10], dtype= torch.int)

In [21]:
x.mul(y)

tensor([25, 40, 50], dtype=torch.int32)

In [25]:
z=x.dot(y)
z

tensor(115, dtype=torch.int32)

In [29]:
p=torch.mul(x,y).sum()
p

tensor(115)